### ISSUE TITLE
HTML injection is possible

### ISSUE THREAD

**Issue by alixcan** [Matildevoldsen/wire-comments#4]
### What happened?

When i tried to comment with `<script>alert(222);</script>` it will save data and when i refresh the page i will see the alert message.

And if you comment with `<?php echo 'Test'; ?>` message will not display but it will saved.

### How to reproduce the bug

Just comment with `<script>alert(222);</script>` or `<?php echo 'Test'; ?>`

### Package Version

0.3.7

### PHP Version

8.2.0

### Laravel Version

11.9

### Which operating systems does with happen with?

macOS

**Comment by Matildevoldsen** [comment]
Hi! 

I'll provide an MR for it this weekend. Thank you for spotting it, wire-comments is still in beta so I'm still discovering bugs in a lot of places.

**Comment by Matildevoldsen** [comment]
I've created a pull request for it now 😄
